sns/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'

  resources :posts, except: [:show]do
    post "/like", to: "likes#like"
    resources :comments, only: [:create, :destroy]
  end
  
  resources :follows, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sns/app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, PostImageUploader
    belongs_to :user
    has_many :likes
    has_many :commets
    has_many :liked_users, through: :likes, source: :user
end

sns/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

  def create
    new_comment = Comment.new(content: params[:content],
                              post_id: params[:post_id],
                              user_id: current_user.id)
    new_comment.save

    redirect_to :back
  end
  
  def destroy
    @comment.destroy
    redirect_to :back
  end

  private
  def check_ownership!
    @comment = Comment.find_by(id: params[:id])
    redirect_to root_path if @comment.user.id != current_user.id
  end
  
end

sns/app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!

  def create
    Follow.create(followed_id: params[:followed_id],
                  follower_id: current_user.id)
    redirect_to :back
  end

  def destroy
    Follow.find_by(followed_id: params[:id],
                   follower_id: current_user.id).destroy
    redirect_to :back
  end
end

sns/app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!

  def like_toggle
    like = Like.find_by(user_id: current_user.id,
                        post_id: params[:post_id])

    if like.nil?
      Like.create(user_id: current_user.id,
                  post_id: params[:post_id])
    else
      like.destroy
    end

    redirect_to :back
  end
end

sns/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_ownership, only: [:edit, :update, :destroy]

  
  def index
      @posts = Post.all.order('created_at desc')
      @posts_count = current_user.posts.length
  end
  
  def new
  end
  
  def create
    new_post = Post.new(user_id: current_user.id, 
                        content: params[:contect],
                        image: params[:image])
    if new_post.save
      redirect_to root_path
    else
      redirect_to new_post_path
    end
  end
  
  def edit
  end
  
  def update
    @post.content = params[:content]
    
    if @post.save
        redirect_to root_path
    else
        render :edit
    end
  end
  
  def destroy
    @post.destroy
    redirect_to root_path
  end

  private
  def check_ownership
    @post = Post.find_by(id: params[:id])
    redirect_to root_path if @post.user.id != current_user.id
  end
  
end

sns/app/views/posts/_post.html.erb
<div class="card post">
    <div class="card-content">
        <if post.user.avatar %>
            <img class="circle thumbnail" src="<%=post.user.avatar.thumb.url%>"/>
        <% end %>
        <span class="card-title"><%= post.user.name %></span>
        <span><%= post.created_at %></span>
        <% if user_signed_in? && current_user != post.user %>
            <% if current_user.followings.include?(post.user) %>
                <%= form_tag follow_path(post.user.id), method: :delete, class: "right" do %>
                 <button class="btn">팔로우 취소</button>
                <% end %>
            <% else %>
             <%= form_tag follows_path, class: "right" do %>
                <input type="hidden" name="followed_id" value="<%= post.user.id%>" />
                <button class="btn">팔로우</button>
             <% end %>
            <% end %>
        <% end %>
        <div class="card-image">
            <% if post.image.url %>
                <img src="<%= post.image.url %>">
            <% end %>
        </div>
        <p class="pre-line"><%= post.content %></p>
    </div>

    <div class="card-action">
         <%= post.likes.size %> 명이 좋아합니다.
         <% if current_user.is_like?(post) %>
            <%= link_to "좋아요 취소", post_like_path(post), method: "post" %>
         <% else $>
            <%= link_to "좋아요", post_like_path(post), method: "post" %>
         <% end %>
         
         <% if current_user.id == post.user_id %>
            <%= link_to "삭제", post_path(post), method: "delete", class: "right" %>
            <%= link_to "수정", edit_post_path(post), class: "right" %>
         <% end %>
         
         <%= form_tag post_comments_path(post) do %>
          <div class="input-field">
            <%= text_area_tag :content, nil, class: "materialize-textarea", placeholder: "댓글을 작성해주세요.", required: true %>
          </div>
          <div class="input-field">
            <%= button_tag "댓글 쓰기", class: "btn" %>
          </div>
         <% end %>
         <% if post.comments.present? %>
          <ul class="collection">
          <% post.comments.each do |comment| %>
            <li class="collection-item">
               <span class="title"><%= comment.user.name %></span>
               <span class="right"><%= comment.created_at %></span>
                
              <p><%= comment.content %></p>
              <% if comment.user.id == current_user.id %>
                <div><%= link_to "삭제", post_comment_path(post, comment), method: "delete" %></div>
              <% end %>
            </li>
          <% end %>
          </ul>
        <% end %>
    </div>
</div>

sns/app/views/posts/index.html.erb
<div class="container">
    <div class="row">
        <div class="col s12 m4">
            <div class="card user-info">
                <% unless current_user.avatar.url.nil? %>
                <div class="card-image">
                    <img src=<%= current_user.avatar.url %>" />
                </div>
                <% end %>
                <div class="card-content">
                    <div class="card-title"><%= current_user.name %></div>
                    <p>이메일 : <%= current_user.email %></p>
                    <p>올린 글 개수 : <%= @posts_count %></p>
                    <p>팔로워 : <%= current_user.followers.length %></p>
                    <p>팔로잉 : <%= current_user.followings.length %></p>
                    <%= link_to new_post_path do %>
                        <button class="btn">글 쓰기</button>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="col s12 m8">
            <% @posts.each do |post| %>
               <%= render partial: "post", object:post %>
            <% end %>
        </div>
    </div>
</div>

sns/app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="card col s12">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">새 글 작성하기 </span></span>
          <%= form_tag posts_path, multipart: true do %>
            <div class="input-field">
              <$= file_field_tag :image %>
            </div>
            
            <div class = "input-field">
              <%= text_area_tag :content, nil, class: "materialize-textarea", placeholder: "무슨생각을 하고 있나요?" %>
            </div>
            
            <div class ="input-field">
              <%= button_tag "작성하기", class: "btn" %>
            </div>
          <p>I am a very simple card. I am good at containing small bits of information.
          I am convenient because I require little markup to use effectively.</p>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>